name: AntiNetherRoof
version: '1.1.0'
main: geometrical.anr.AntiNetherRoof
api-version: '1.12'
load: STARTUP
authors: [ Geometrical ]
description: If someone tries to get onto the roof it will teleport them down to the closest air block.
website: https://modrinth.com/user/Geometrical

permissions:
  anr.bypass:
    description: Allows a player to bypass Nether roof teleportation.
    default: op